// 2026-08-12: URL·publishable key 하드코딩 (Plan B).
// Lovable 프리뷰가 .env 계열 파일을 무시하고 런타임에 다른 값(bhuwic)을 주입해
// 서울 정본 DB(okeeihfmagfogvuxzszb) 대신 오참조하는 문제를 차단하기 위함.
// 아래 두 값은 브라우저 번들에 노출되는 공개용(anon publishable) 값이라 보안 손실 없음.
// service_role 키는 절대 넣지 말 것. 값은 .env.production 에서 그대로 옮김.
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okeeihfmagfogvuxzszb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_1FqDFPJRQA2DJDNQUpOz-g_xDC1Apv7";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});